name: Check links

# ↓ lock down top‐level permissions to only what we use
permissions:
  contents: read             # we only need to checkout code
  actions: read              # to query workflows/runs
  pull-requests: write       # to comment on or label PRs

on:
  pull_request:
    branches: [ '**' ]
    paths:
      - '**/*.md'
      - '**/*.html'
      - '**/*.htm'
      - '**/*.txt'
      - '**/*.rst'
  push:
    branches: [ 'main' ]
    paths:
      - '**/*.md'
      - '**/*.html'
      - '**/*.htm'
      - '**/*.txt'
      - '**/*.rst'
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      statuses: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  #v4.2.2
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: "--base . --cache --max-cache-age 1d ."
